on:
  push:
    branches:
      - main
name: release
jobs:
  release-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: '@as-integrations/h3'
